version: "2.1"
services:
  web:
    image: daerodriguezme/javel_back:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DB_CONTAINER: 'mongo'
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"

volumes:
  mongodb:
  mongodb_config: