version: "2.1"
services:
  web:
    image: daerodriguezme/javel_back:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    restart: always
    command: mongod
    env_file:
      - .env 
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"

volumes:
  mongodb:
  mongodb_config: